// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatbuf

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RawQuoteBatch struct {
	_tab flatbuffers.Table
}

func GetRootAsRawQuoteBatch(buf []byte, offset flatbuffers.UOffsetT) *RawQuoteBatch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RawQuoteBatch{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRawQuoteBatch(buf []byte, offset flatbuffers.UOffsetT) *RawQuoteBatch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RawQuoteBatch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RawQuoteBatch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RawQuoteBatch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RawQuoteBatch) RawQuotes(obj *RawQuote, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RawQuoteBatch) RawQuotesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RawQuoteBatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RawQuoteBatchAddRawQuotes(builder *flatbuffers.Builder, rawQuotes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(rawQuotes), 0)
}
func RawQuoteBatchStartRawQuotesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RawQuoteBatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
